---
apiVersion: v1
kind: Service
metadata:
  name: jstubbs-test-redis-service
  labels:
    env: test
    username: jstubbs
spec:
  type: ClusterIP
  selector:
    app: jstubbs-test-redis
  ports:
  - name: jstubbs-test-redis-port
    port: 6379
    targetPort: 6379